"""
Download / organise the assets for the realistic OR panel.

    python tools/get_assets.py            # fetch everything that can be fetched
    python tools/get_assets.py --check    # only report what is present

Fetched automatically (from GitHub, all CC0 1.0):
    assets/src/makehuman/   MakeHuman base body, skeleton, skin weights, eyes
                            -> used to build the posed surgeon and patient
Generated locally (no download, CC0 - made by this project):
    floor / wall / drape textures (procedural), OR props (table, lamps,
    anesthesia machine, trolley, IV stand, robot carts, drapes)

Optional, manual (put the files where shown; the renderer uses them if found):
    assets/hdri/or.hdr                 an indoor HDRI (e.g. Poly Haven, CC0)
    assets/textures/floor.jpg|png      a vinyl / epoxy floor texture
    assets/textures/wall.jpg|png       a tiled wall texture
    assets/humans/patient_custom.glb   your own human exports (MakeHuman /
    assets/humans/surgeon_custom.glb   Mixamo->glTF). Must already be posed
                                       and in metres, Z up, origin at the feet.
Anything missing falls back to the built-in versions with a warning.
"""
import argparse
import os
import sys
import urllib.request

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, HERE)
os.chdir(HERE)
import config as cfg                                         # noqa: E402

RAW = ("https://raw.githubusercontent.com/makehumancommunity/makehuman/"
       "master/makehuman/data/")
MH_FILES = [
    "3dobjs/base.obj",
    "rigs/default.mhskel",
    "rigs/default_weights.mhw",
    "eyes/high-poly/high-poly.obj",
    "eyes/high-poly/high-poly.mhclo",
    "eyes/materials/brown_eye.png",
]
LICENSE_URL = ("https://raw.githubusercontent.com/makehumancommunity/"
               "makehuman/master/LICENSE.ASSETS.md")

MANUAL = [
    ("hdri/or.hdr", "Indoor HDRI for reflections (Poly Haven, CC0)"),
    ("textures/floor.jpg", "Floor texture (Poly Haven / ambientCG, CC0)"),
    ("textures/wall.jpg", "Tiled wall texture (Poly Haven / ambientCG, CC0)"),
    ("humans/patient_custom.glb", "Own patient export (optional)"),
    ("humans/surgeon_custom.glb", "Own surgeon export (optional)"),
]


def fetch(url, dst):
    os.makedirs(os.path.dirname(dst), exist_ok=True)
    if os.path.isfile(dst) and os.path.getsize(dst) > 0:
        return "present"
    try:
        with urllib.request.urlopen(url, timeout=60) as r, \
                open(dst + ".part", "wb") as f:
            f.write(r.read())
        os.replace(dst + ".part", dst)
        return "downloaded"
    except Exception as e:                                  # noqa: BLE001
        return f"FAILED ({e})"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    root = cfg.ASSET_DIR
    mh = os.path.join(root, "src", "makehuman")
    print("MakeHuman (CC0) ->", mh)
    for f in MH_FILES + ["LICENSE.ASSETS.md"]:
        dst = os.path.join(mh, os.path.basename(f) if f == "LICENSE.ASSETS.md"
                           else f.replace("3dobjs/", "").replace("rigs/", ""))
        if a.check:
            st = "present" if os.path.isfile(dst) else "missing"
        else:
            url = LICENSE_URL if f == "LICENSE.ASSETS.md" else RAW + f
            st = fetch(url, dst)
        print(f"  {f:38s} {st}")
    print("Optional manual assets:")
    for rel, what in MANUAL:
        p = os.path.join(root, rel)
        print(f"  {'OK     ' if os.path.isfile(p) else 'absent '} {p:42s} {what}")
    write_licenses(root)
    print(f"licenses -> {os.path.join(root, 'LICENSES.md')}")


def write_licenses(root):
    os.makedirs(root, exist_ok=True)
    with open(os.path.join(root, "LICENSES.md"), "w", encoding="utf-8") as f:
        f.write("""# Asset licences

| Asset | Source | Licence |
|---|---|---|
| Human body, skeleton, weights, eyes (src/makehuman) | MakeHuman Community, github.com/makehumancommunity/makehuman | CC0 1.0 (see src/makehuman/LICENSE.ASSETS.md) |
| Posed surgeon and patient (built at run time from the above) | this project | CC0 1.0 |
| Robot arms | KUKA LBR iiwa model shipped with pybullet_data (Bullet Physics) | zlib (Bullet) |
| Procedural textures, OR table, lamps, anesthesia machine, trolley, IV stand, carts, drapes | generated by props.py, this project | CC0 1.0 |
""")
        for rel, what in MANUAL:
            if os.path.isfile(os.path.join(root, rel)):
                f.write(f"| {rel} | added manually | record its licence here |\n")


if __name__ == "__main__":
    main()
